# Generated by Django 5.1.4 on 2024-12-15 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('description', models.TextField(verbose_name='Описание группы')),
                ('creation_date', models.DateField(verbose_name='Дата создания группы')),
                ('image', models.ImageField(upload_to='groups', verbose_name='Изображение группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('description', models.TextField(verbose_name='Описание альбома')),
                ('release_date', models.DateField(verbose_name='Дата выпуска альбома')),
                ('cover_image', models.ImageField(upload_to='albums', verbose_name='Обложка альбома')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='main.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя участника')),
                ('biography', models.TextField(verbose_name='Биография участника')),
                ('role', models.CharField(max_length=100, verbose_name='Роль в группе')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='members', verbose_name='Фотография участника')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Участник группы',
                'verbose_name_plural': 'Участники группы',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название песни')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание песни')),
                ('duration', models.DurationField(verbose_name='Длительность песни')),
                ('audio_file', models.FileField(upload_to='songs', verbose_name='Аудиофайл')),
                ('lyrics', models.TextField(verbose_name='Текст песни')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='main.album', verbose_name='Альбом')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='main.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
    ]
